# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/sierrarowerra
spring.datasource.username=sierrarowerra_user
spring.datasource.password=123QWElkjasdA412
spring.jpa.hibernate.ddl-auto=update

# Stripe Settings
stripe.api.secret-key=sk_test_51S1Rkw8prmVxapluOeaCP2si6TwuEgnhns7pLIyVDArMzprOD6JoScPFEM42ogmel80Lz3ev38gZbmRS49OkaUaZ00ylotAfAb
stripe.api.public-key=pk_test_51S1Rkw8prmVxapluZwFVaaXadkGNCdWtfAfZ3nMoihjNHIIhEbGnSFUgJWlGorVFXnLF1YjRS1c3jjdsEHlEEbB900MlT99JHX
stripe.webhook.secret=whsec_678459d23df16a77fbb5ecc73baf89cdb015236fe2ccffd583d9b4bc729af0f0
spring.jpa.open-in-view=false

# File Storage
file.upload-dir=uploads/


# ===============================
# = OAUTH2 GOOGLE CONFIGURATION =
# ===============================
app.oauth2.authorizedRedirectUri=http://localhost:4200/oauth2/redirect
spring.security.oauth2.client.registration.google.client-id=819340343667-3kbpi94skfro3mqd4ep93lnrn8i1am73.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email

logging.level.org.springframework.security=DEBUG
