# Database
spring.datasource.url=jdbc:postgresql://localhost:5433/sierrarowerra
spring.datasource.username=sierrarowerra_user
spring.datasource.password=123QWElkjasdA412
spring.jpa.hibernate.ddl-auto=update

# Stripe Settings
stripe.api.secret-key=
stripe.api.public-key=
stripe.webhook.secret=
spring.jpa.open-in-view=false

# File Storage
file.upload-dir=uploads/


# ===============================
# = OAUTH2 GOOGLE CONFIGURATION =
# ===============================
app.oauth2.authorizedRedirectUri=http://localhost:4200/oauth2/redirect
spring.security.oauth2.client.registration.google.client-id=
spring.security.oauth2.client.registration.google.client-secret=
spring.security.oauth2.client.registration.google.scope=openid,profile,email

logging.level.org.springframework.security=DEBUG
