spring.application.name=sierrarowerra

# Default to local profile
spring.profiles.active=local

# JWT Settings
sierrarowerra.app.jwtSecret=======================sierrarowerra==========================
sierrarowerra.app.jwtExpirationMs=86400000

# CORS Configuration
sierrarowerra.app.cors.allowed-origins=http://localhost:3000,http://localhost:4200,http://localhost:8081

# App-specific properties
app.frontend.base-url=http://localhost:4200

# Email Configuration (Gmail Example)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pavelvdotsenko@gmail.com
spring.mail.password=tjcpseiumhzgmkbq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
